/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Tam_bloque.java
 *
 * Created on 28-may-2013, 16:20:06
 */

package teoriadealinfo;

import javax.swing.JOptionPane;

/**
 *
 * @author Mauricio
 */
public class Tam_bloque extends javax.swing.JDialog {

    public Integer intValor;
    /** Creates new form Tam_bloque */
    public Tam_bloque(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jrdb1 = new javax.swing.JRadioButton();
        jrdb2 = new javax.swing.JRadioButton();
        jrdb3 = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        jbtnAceptar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setName("Form"); // NOI18N

        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(teoriadealinfo.TeoriadealInfoApp.class).getContext().getResourceMap(Tam_bloque.class);
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, resourceMap.getString("jPanel1.border.title"), javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, resourceMap.getFont("jPanel1.border.titleFont"))); // NOI18N
        jPanel1.setName("jPanel1"); // NOI18N

        buttonGroup1.add(jrdb1);
        jrdb1.setFont(resourceMap.getFont("jrdb1.font")); // NOI18N
        jrdb1.setText(resourceMap.getString("jrdb1.text")); // NOI18N
        jrdb1.setName("jrdb1"); // NOI18N
        jrdb1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrdb1ActionPerformed(evt);
            }
        });

        buttonGroup1.add(jrdb2);
        jrdb2.setFont(resourceMap.getFont("jrdb2.font")); // NOI18N
        jrdb2.setText(resourceMap.getString("jrdb2.text")); // NOI18N
        jrdb2.setName("jrdb2"); // NOI18N

        buttonGroup1.add(jrdb3);
        jrdb3.setFont(resourceMap.getFont("jrdb3.font")); // NOI18N
        jrdb3.setText(resourceMap.getString("jrdb3.text")); // NOI18N
        jrdb3.setName("jrdb3"); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jrdb1)
                .addGap(53, 53, 53)
                .addComponent(jrdb2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 52, Short.MAX_VALUE)
                .addComponent(jrdb3)
                .addGap(36, 36, 36))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jrdb1)
                    .addComponent(jrdb3)
                    .addComponent(jrdb2))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        jLabel1.setFont(resourceMap.getFont("jLabel1.font")); // NOI18N
        jLabel1.setText(resourceMap.getString("jLabel1.text")); // NOI18N
        jLabel1.setName("jLabel1"); // NOI18N

        jbtnAceptar.setFont(resourceMap.getFont("jbtnAceptar.font")); // NOI18N
        jbtnAceptar.setText(resourceMap.getString("jbtnAceptar.text")); // NOI18N
        jbtnAceptar.setName("jbtnAceptar"); // NOI18N
        jbtnAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnAceptarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(40, 40, 40))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(69, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(56, 56, 56))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(169, Short.MAX_VALUE)
                .addComponent(jbtnAceptar)
                .addGap(159, 159, 159))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jbtnAceptar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jrdb1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrdb1ActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_jrdb1ActionPerformed

    private void jbtnAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnAceptarActionPerformed

        if(jrdb1.isSelected()==false & jrdb2.isSelected()==false & jrdb3.isSelected()==false){
            JOptionPane.showMessageDialog(null,"Seleccione una opción");
        } else
            if(jrdb1.isSelected()==true) intValor=1024;
            else
                if(jrdb2.isSelected()==true) intValor=512;
                else{
                    intValor=256;
                    dispose();
                }

        // TODO add your handling code here:
}//GEN-LAST:event_jbtnAceptarActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Tam_bloque dialog = new Tam_bloque(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton jbtnAceptar;
    private javax.swing.JRadioButton jrdb1;
    private javax.swing.JRadioButton jrdb2;
    private javax.swing.JRadioButton jrdb3;
    // End of variables declaration//GEN-END:variables

}
